apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-name-ip-app-deployment
  labels:
    app: hello-name-ip-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hello-name-ip-app
  template:
    metadata:
      labels:
        app: hello-name-ip-app
    spec:
      containers:
        - name: "hello-name-ip-app"
          image: "{{ .Values.image.nameIp.repository }}:{{ .Values.image.nameIp.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:                             # resources: Define resource requests and limits
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"