apiVersion: v1
kind: Service
metadata:
  name: hello-name-ip-app-service
  labels:
    app: hello-name-ip-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8081
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: hello-name-ip-app
