apiVersion: v1
kind: Service
metadata:
  name: hello-world-app-service
  labels:
    app: hello-world-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8083
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: hello-world-app
